// Design tokens.
//
// The dark palette has to exist twice in the CSS: once inside a
// prefers-color-scheme media query for people who never touch a toggle, and
// once on a [data-theme="dark"] attribute for people who do. CSS has no
// @extend, so hand-maintaining both copies guarantees they eventually drift,
// and the drift is invisible until someone with a dark OS switches manually.
// Generating both from this one object removes the possibility.

export const SCALE = `
  /* ---- spacing: 4px base, no ad-hoc rem values anywhere ---- */
  --sp-1: 0.25rem;
  --sp-2: 0.5rem;
  --sp-3: 0.75rem;
  --sp-4: 1rem;
  --sp-5: 1.5rem;
  --sp-6: 2rem;
  --sp-7: 3rem;
  --sp-8: 4rem;

  /* ---- type scale ---- */
  --fs-xs:   0.75rem;
  --fs-sm:   0.8125rem;
  --fs-mono: 0.8125rem;
  --fs-base: 0.9375rem;
  --fs-md:   1rem;
  --fs-lg:   1.125rem;
  --fs-xl:   1.375rem;
  --fs-h1:   clamp(1.5rem, 1.15rem + 1.6vw, 2.125rem);

  --lh-tight: 1.2;
  --lh-snug:  1.35;
  --lh-body:  1.55;

  --fw-normal: 400;
  --fw-medium: 500;
  --fw-bold:   600;

  /* ---- radii: squared, deliberately. No pill radius exists here. ---- */
  --r-xs: 3px;
  --r-sm: 5px;
  --r-md: 8px;
  --r-lg: 10px;

  --bw: 1px;
  --bw-accent: 3px;

  --dur-fast: 110ms;
  --dur-base: 170ms;
  --ease: cubic-bezier(0.2, 0, 0.13, 1);

  --w-prose:   68ch;
  --w-content: 1040px;
  --w-search:  620px;

  /* Segoe UI Variable is what this audience already reads administrative
     interfaces in, and using it costs zero requests and zero layout shift. */
  --font-ui: system-ui, -apple-system, "Segoe UI Variable Text", "Segoe UI", Roboto,
    "Helvetica Neue", Arial, sans-serif;
  /* Chosen for a distinguishable zero and clear 1/l/I separation, which
     matters when the page is mostly GUIDs. */
  --font-mono: ui-monospace, "Cascadia Mono", "SF Mono", "Segoe UI Mono", Menlo, Consolas,
    "Liberation Mono", monospace;
`;

// Contrast ratios in the comments are measured, not assumed.
export const LIGHT = {
  '--bg': '#F2F7FE',
  '--surface': '#FFFFFF',
  '--surface-sunk': '#E9F0FA',
  '--surface-hover': '#E4EDFA',
  '--text': '#091A33',
  '--text-muted': '#4A5C78',
  '--text-faint': '#5C6E88',
  '--accent': '#0248CE',
  '--accent-hover': '#013CAE',
  '--accent-wash': '#DCE9FF',
  '--on-accent': '#FFFFFF',
  '--border': '#D6E0EF',
  '--border-strong': '#66809F',
  '--focus': '#0248CE',
  '--ok': '#0B7A5E',
  '--ok-wash': '#CAF4E8',
  '--warn-wash': '#FDF3D4',
  '--shadow-pop': '0 1px 2px rgba(9, 26, 51, 0.06), 0 8px 24px rgba(9, 26, 51, 0.12)',
  'color-scheme': 'light',
};

export const DARK = {
  '--bg': '#091A33',
  '--surface': '#0F223D',
  '--surface-sunk': '#0B1B31',
  '--surface-hover': '#16304F',
  '--text': '#F2F7FE',
  '--text-muted': '#9DAABC',
  '--text-faint': '#8698AF',
  // Bright Blue is 2.34:1 on this navy and unreadable, so dark mode uses a
  // pale accent instead. Every component references var(--accent) and never a
  // literal, which is what makes the swap automatic.
  '--accent': '#8EC5FF',
  '--accent-hover': '#BEDBFF',
  '--accent-wash': '#16345C',
  '--on-accent': '#091A33',
  '--border': '#1E3557',
  '--border-strong': '#4A648C',
  '--focus': '#8EC5FF',
  '--ok': '#00BC7D',
  '--ok-wash': '#004F3B',
  '--warn-wash': '#432004',
  '--shadow-pop': '0 12px 32px rgba(2, 9, 19, 0.66)',
  'color-scheme': 'dark',
};

function declarations(palette, indent = '  ') {
  return Object.entries(palette)
    .map(([property, value]) => `${indent}${property}: ${value};`)
    .join('\n');
}

/** Emit the palette layer: light default, dark by preference and by attribute. */
export function renderTokensCss() {
  return `/* Generated by src/render/tokens.mjs. Do not edit by hand. */
:root {
${declarations(LIGHT)}
${SCALE.trimEnd()}
}

/* Dark for people who never touch the toggle. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${declarations(DARK, '    ')}
  }
}

/* Dark for people who did. Same values, generated from the same object. */
:root[data-theme="dark"] {
${declarations(DARK)}
}

/* Light forced on, overriding a dark OS. */
:root[data-theme="light"] {
${declarations(LIGHT)}
}
`;
}
